# Generated by Django 2.2 on 2020-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('pass_phrase', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
